name: Packer Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  packer-build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3

      - name: Install Ansible & Ansbile Galaxy
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Install Ansible roles
        run: ansible-galaxy install RedHatOfficial.rhel9_stig -p ./ansible

      - name: Install Packer plugins
        run: packer init ./packer/

      - name: Run Packer build
        run: cd packer && packer build .